apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.2.0 (99f88ef)
  creationTimestamp: null
  labels:
    io.kompose.service: resume
  name: resume
  namespace: kube-public
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: resume
    spec:
      containers:
      - image: mayankt/resume:master
        name: resume
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.2.0 (99f88ef)
  creationTimestamp: null
  labels:
    io.kompose.service: resume
  name: resume
  namespace: kube-public
spec:
  ports:
  - name: "resumesite"
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: resume
  type: LoadBalancer
status:
  loadBalancer: {}
